### ISSUE TITLE
Sort class list

### ISSUE THREAD

**Issue by hschletz** [phpDocumentor/template.clean#2] opened 2013-08-11 10:40 UTC
The class list is unsorted, making it difficult to locate a class without using my browser's page search. This applies to the left pane and to the list in the main view.

**Comment by bretrzaun** [comment] 2014-01-22 11:13
+1

**Comment by mvriel** [comment] 2014-01-22 11:20
This should be fixed on the development version; we will review this and include the fix with the next release

**Comment by bretrzaun** [comment] 2014-01-22 11:28
Just found out about this already being in code.
Unfortunately I found no way on how to use the master version of the template via Composer.
Any idea?

**Comment by mvriel** [comment] 2014-01-22 11:35
If you are proficient with Composer you can change the entry for the clean template to use dev-master as version and then execute the command `php composer.phar update phpdocumentor/template-clean`

**Comment by bretrzaun** [comment] 2014-01-22 12:51
I tried that before - however I got:

```
Your requirements could not be resolved to an installable set of packages.

Problem 1
- phpdocumentor/phpdocumentor v2.2.0 requires phpdocumentor/template-clean ~1.0 -> no matching package found.
- phpdocumentor/phpdocumentor v2.2.0 requires phpdocumentor/template-clean ~1.0 -> no matching package found.
- Installation request for phpdocumentor/phpdocumentor == 2.2.0.0 -> satisfiable by phpdocumentor/phpdocumentor[v2.2.0].
```

I have this in my composer.json (require-dev):

```
"phpdocumentor/phpdocumentor" : "~2.1",
"phpdocumentor/template-clean" : "dev-master",
```

**Comment by doubleforte** [comment] 2014-03-13 17:17
Just installed v2.3.1 of phpdoc and the classes don't seem to be in any specific order. According to this thread, it's supposed to be fixed, but either it's not or I'm doing something wrong. Help?
![sort-order](https://f.cloud.github.com/assets/6754378/2412481/3d0ffc4e-aad3-11e3-8e93-a9b952d6b35a.jpg)

**Comment by mvriel** [comment] 2014-03-15 08:51
@doubleforte the source suggests to me that it _should_ be fixed. I will investigate why it doesn't seem to be sorted

**Comment by mvriel** [comment] 2014-03-15 18:26
@doubleforte I have tried to reproduce your situation using the following script:

```
<?php
class BC_Score {}
class BC_InstrumentIndex {}
class BC_AdminModuleIndex {}
class BC_Staff {}
class BC_Invoice {}
class BC_Instrument {}
class BC_EventIndex {}
class BC_BlueCloud {}
class BC_Event {}
```

and had the following output:

![clean-ordering](https://f.cloud.github.com/assets/193704/2429168/33581374-ac6f-11e3-8390-c5952e1ea2ab.png)

Which does not match your findings. Can you tell me how you installed phpDocumentor? If it is via composer: which package version has the template-clean package?

**Comment by doubleforte** [comment] 2014-03-15 19:10
Yikes! That's what it's supposed to look like!

I installed via PEAR:

pear channel-discover pear.phpdoc.org
pear install phpdoc/phpDocumentor

If it makes a difference, each class lives in its own file (BC_Event.php,
BC_EventIndex.php, etc) and all the classes are part of @package BlueCloud

Thanks for your help!
brian

**Comment by mvriel** [comment] 2014-03-17 08:17
When I use the version on PEAR I get the same results as you and the list is not ordered. Perhaps I did not update the clean template to the latest tag during deployment? Gonna fix it :)

**Comment by mvriel** [comment] 2014-03-17 08:34
Apaprently I had not tagged the latest changes in the clean template; which meant that the release did not contain those changes. I have just tagged the latest version.

The easiest way until I do a new release (which is planned for the weekend of March 30th) is to run a composer update for the template-clean package in your phpDocumentor project folder

**Comment by mvriel** [comment] 2014-03-17 08:39
Since this issue is quite clear and could not end in any other way than success. I am going to close it. Should my conclusion be erroneous or more questions arise, please comment in this issue and I will reopen it

**Closed as completed by mvriel** 2014-03-17 08:39 UTC
